### ISSUE TITLE
Very verbose logs on the kvdb prometheus exporter

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot-introspector#108] opened 2022-09-12 10:01 UTC
When running the kvdb prometheus exporter with `polkadot-introspector -vv kvdb --db data/chains/versi_v1_9/db/full/ --db-type rocksdb prometheus`, I have the following log being spammed:

```
[2022-09-12T09:56:52.980546Z DEBUG polkadot_introspector::kvdb::prometheus] sleeping to unload database
[2022-09-12T09:56:53.543644Z DEBUG polkadot_introspector::kvdb::prometheus] sleeping to unload database
[2022-09-12T09:56:53.847615Z DEBUG polkadot_introspector::kvdb::prometheus] sleeping to unload database
[2022-09-12T09:56:54.399472Z DEBUG polkadot_introspector::kvdb::prometheus] sleeping to unload database
```

**Comment by sandreim** [comment] 2022-09-12 10:01
Cc @vstakhov

**Comment by vstakhov** [comment] 2022-09-12 11:39
But why do you run it with debug logs support `-vvv` in the first place?

**Comment by vstakhov** [comment] 2022-09-12 15:45
I'd suggest to keep only one `-v` as I usually put useful but not noisy information on `info` level. Probably, that message about sleeping should go to the `trace` level...

**Comment by vstakhov** [comment] 2022-09-13 08:14
I believe that the issue should be fixed now.

**Comment by sandreim** [comment] 2022-09-13 08:43
paritytech/polkadot-introspector:e1fe8394

**Comment by sandreim** [comment] 2022-09-13 14:14
<img width="1709" alt="Screenshot 2022-09-13 at 17 13 32" src="https://user-images.githubusercontent.com/54316454/189924513-9a744f26-e8d8-40ba-b9bc-8497c3a3f1ef.png">

The issue is fixed as per the funky looking charts.

**Closed by sandreim** 2022-09-13 14:14 UTC
Labels: bug
